# Auto generated by LangBot Plugin SDK.
# Please refer to https://langbot.app/docs/en/plugin/dev/tutor.html for more details.
from __future__ import annotations

from typing import Any, AsyncGenerator

from langbot_plugin.api.definition.components.command.command import Command, Subcommand
from langbot_plugin.api.entities.builtin.command.context import ExecuteContext, CommandReturn

import os
import psutil


class SysStat(Command):

    def __init__(self):
        super().__init__()

        @self.subcommand(
            name="",
            help="View system status including CPU, memory, and disk usage",
            usage="sysstat",
            aliases=["sys"],
        )
        async def show_status(self, context: ExecuteContext) -> AsyncGenerator[CommandReturn, None]:
            """Show system status"""
            try:
                # Get system information
                core_mem = psutil.Process(os.getpid()).memory_info().rss / 1024 / 1024
                sysmem_info = psutil.virtual_memory()
                cpu_info = psutil.cpu_times
                disk_info = psutil.disk_usage('/')
                cpu_ststs = psutil.cpu_stats()
                cpu_freq = psutil.cpu_freq()

                # Build response text
                res = f"""====系统状态====
进程内存占用: {core_mem:.2f}MB
总内存: {sysmem_info.total / 1024 / 1024:.2f}MB
已用内存: {sysmem_info.used / 1024 / 1024:.2f}MB
空闲内存: {sysmem_info.free / 1024 / 1024:.2f}MB
内存使用率: {sysmem_info.percent:.2f}%
用户态CPU时间: {cpu_info().user:.2f}秒
系统态CPU时间: {cpu_info().system:.2f}秒
空闲CPU时间: {cpu_info().idle:.2f}秒
CPU使用率: {psutil.cpu_percent(interval=1):.2f}%
CPU逻辑核心数: {psutil.cpu_count()}
CPU物理核心数: {psutil.cpu_count(logical=False)}
CPU当前频率: {cpu_freq.current:.2f}MHz
总磁盘空间: {disk_info.total / 1024 / 1024 / 1024:.2f}GB
已用磁盘空间: {disk_info.used / 1024 / 1024 / 1024:.2f}GB
空闲磁盘空间: {disk_info.free / 1024 / 1024 / 1024:.2f}GB
磁盘使用率: {disk_info.percent:.2f}%
============"""

                yield CommandReturn(
                    text=res.strip(),
                )
            except Exception as e:
                yield CommandReturn(
                    error=f"获取系统状态失败: {str(e)}",
                )
