apiVersion: v1
kind: EventListener
metadata:
  name: default
  label:
    en_US: DailyLimitListener
    zh_Hans: 每日限制监听器
spec:
execution:
  python:
    path: default.py
    attr: DefaultEventListener
