# Auto generated by LangBot Plugin SDK.
# Please refer to https://langbot.app/docs/en/plugin/dev/tutor.html for more details.
from __future__ import annotations

from langbot_plugin.api.definition.plugin import BasePlugin

class GoogleSearch(BasePlugin):

    def __init__(self):
        super().__init__()

    async def initialize(self) -> None:
        pass