# Auto generated by LangBot Plugin SDK.
# Please refer to https://langbot.app/docs/en/plugin/dev/tutor.html for more details.
from __future__ import annotations

from langbot_plugin.api.definition.plugin import BasePlugin

class EssentialCommands(BasePlugin):

    def __init__(self):
        super().__init__()
        self.language = 'en_US'  # Default language

    async def initialize(self) -> None:
        # Get language from config
        if self.config and 'language' in self.config:
            self.language = self.config['language']
        print(f"EssentialCommands language set to: {self.language}")

    def get_language(self) -> str:
        """Get the configured language."""
        return self.language
