# Auto generated by LangBot Plugin SDK.
# Please refer to https://langbot.app/docs/en/plugin/dev/tutor.html for more details.
from __future__ import annotations

import asyncio
import datetime
import logging
from typing import Any

from langbot_plugin.api.definition.plugin import BasePlugin
from langbot_plugin.api.entities.builtin.platform import message as platform_message


class ScheNotify(BasePlugin):
    """
    Schedule notification plugin.
    Allows users to schedule notifications using natural language through LLM.
    """

    def __init__(self):
        super().__init__()
        self.scheduled_events: list[dict[str, Any]] = []
        self.logger = logging.getLogger(__name__)

    async def initialize(self) -> None:
        """Initialize the plugin and start the check loop"""
        # Start the background task to check scheduled events
        asyncio.create_task(self._check_loop_wrapper())
        self.logger.info("ScheNotify plugin initialized")

    async def _check_loop_wrapper(self):
        """Wrapper for the check loop to handle continuous execution"""
        while True:
            try:
                await self._check_scheduled_events()
            except Exception as e:
                self.logger.error(f"Error in check loop: {e}", exc_info=True)
            await asyncio.sleep(60)  # Check every minute

    async def _check_scheduled_events(self):
        """Check scheduled events and send notifications for due events"""
        now = datetime.datetime.now()
        self.logger.info(f"Checking scheduled events at {now}")
        self.logger.debug(f"Scheduled events: {self.scheduled_events}")

        events_to_remove = []

        for event in self.scheduled_events:
            if now >= event["time"]:
                # Send notification
                try:
                    await self._send_notification(event)
                    events_to_remove.append(event)
                except Exception as e:
                    self.logger.error(f"Failed to send notification: {e}", exc_info=True)

        # Remove sent events
        for event in events_to_remove:
            self.scheduled_events.remove(event)

    async def _send_notification(self, event: dict[str, Any]):
        """
        Send notification message to the session.

        Args:
            event: Event dict containing session info and message
        """
        # Get language setting
        config = self.get_config()
        language = config.get("language", "zh_Hans")
        prefix = "[Notify] " if language == "en_US" else "[Notify] "

        message_chain = platform_message.MessageChain([
            platform_message.Plain(text=f"{prefix}{event['message']}")
        ])

        # Send message using saved session info
        try:
            await self.send_message(
                bot_uuid=event["bot_uuid"],
                target_type=event["target_type"],
                target_id=event["target_id"],
                message_chain=message_chain
            )
        except Exception as e:
            self.logger.error(f"Failed to send message: {e}", exc_info=True)

    async def add_scheduled_event(
        self,
        time: datetime.datetime,
        message: str,
        bot_uuid: str,
        target_type: str,
        target_id: str
    ):
        """
        Add a scheduled event (called from schedule_notify tool).

        Args:
            time: Scheduled time
            message: Notification message
            bot_uuid: Bot UUID
            target_type: "person" or "group"
            target_id: Target ID
        """
        self.scheduled_events.append({
            "time": time,
            "message": message,
            "bot_uuid": bot_uuid,
            "target_type": target_type,
            "target_id": target_id,
        })

    async def get_scheduled_events(self, target_id: str | None = None) -> list[dict[str, Any]]:
        """
        Get scheduled events, optionally filtered by target_id.

        Args:
            target_id: Optional target ID for filtering

        Returns:
            List of scheduled events
        """
        if target_id is None:
            return self.scheduled_events

        # Filter by target_id
        return [
            event for event in self.scheduled_events
            if event.get("target_id") == target_id
        ]

    async def delete_scheduled_event(self, event: dict[str, Any]):
        """
        Delete a scheduled event.

        Args:
            event: Event to delete
        """
        if event in self.scheduled_events:
            self.scheduled_events.remove(event)

    def __del__(self):
        """Cleanup when plugin is unloaded"""
        self.logger.info("ScheNotify plugin unloaded")
