apiVersion: v1
kind: Command
metadata:
  name: mcbot
  label:
    en_US: MCBot
    zh_Hans: Minecraft 助手
  description:
    en_US: 'Manage Minecraft server binding, status and playtime: mcbot / bind / unbind / status / time'
    zh_Hans: '管理 Minecraft 服务器绑定、状态与时长：mcbot / bind / unbind / status / time'
spec:
execution:
  python:
    path: mcbot.py
    attr: MCBot
