import jinja2

plugin_manifest_str = """
apiVersion: v1
kind: Plugin
metadata:
  author: {{ plugin_author }}
  name: {{ plugin_name }}
  repository: '{{ plugin_repository }}'
  version: 0.1.0
  description:
    en_US: {{ plugin_description }}
    zh_CN: {{ plugin_description }}
  label:
    en_US: {{ plugin_label }}
    zh_CN: {{ plugin_label }}
spec:
  config: []
  components: []
execution:
  python:
    path: main.py
    attr: {{ plugin_attr }}
"""

plugin_manifest_template = jinja2.Template(plugin_manifest_str)

main_py_str = """
# Auto generated by LangBot Plugin SDK.
# Please refer to https://docs.langbot.app/en/plugin/dev/tutor.html for more details.
from __future__ import annotations

from langbot_plugin.api.plugin.base import BasePlugin

class {{ plugin_attr }}(BasePlugin):

    def __init__(self):
        super().__init__()

    async def initialize(self) -> None:
        pass
"""

main_py_template = jinja2.Template(main_py_str)

readme_md_str = """
# {{ plugin_name }}

{{ plugin_description }}
"""

readme_md_template = jinja2.Template(readme_md_str)

requirements_txt_str = """
langbot-plugin
"""

requirements_txt_template = jinja2.Template(requirements_txt_str)