apiVersion: v1
kind: Command
metadata:
  name: summary
  label:
    en_US: Summary
    zh_Hans: 群聊总结
  description:
    en_US: 'Summarize recent group chat messages'
    zh_Hans: '总结最近的群聊消息'
spec:
execution:
  python:
    path: summary.py
    attr: Summary
